from ultraconv.processors.utils import download_file, ffmpeg_convert

from ultraconv.processors.aligner_algo import AlignerSimpleAlgo

from ultraconv.processors.pitcher import PitcherUltrastarPitch

from ultraconv.processors.splitter_htdemucs import SplitterDemucs

from ultraconv.processors.transliterator_unidecode import TransliteratorUnidecode
from ultraconv.processors.transliterator_pyicu import TransliteratorICU
from ultraconv.processors.transliterator_kakasi import TransliteratorKakasi
from ultraconv.processors.transliterator_hangul import TransliteratorHangul

PROCESSORS = [AlignerSimpleAlgo, PitcherUltrastarPitch, SplitterDemucs, TransliteratorICU, TransliteratorUnidecode, TransliteratorKakasi, TransliteratorHangul]
